services:
  db:
    image: postgres:15-alpine
    container_name: devboard_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changethis
      - POSTGRES_DB=devboard
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: